// Mocks generated by Mockito 5.4.5 from annotations
// in astromedia/test/modules/home/presenter/home/bloc/astronomical_media_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:astromedia/core/common/responses/results/i_response/i_response_result.dart'
    as _i2;
import 'package:astromedia/modules/home/domain/enums/media_type.dart' as _i7;
import 'package:astromedia/modules/home/domain/i_usecases/i_astronomical_media_usecase.dart'
    as _i3;
import 'package:astromedia/modules/home/domain/models/astronomical_media_model.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeIResponseResult_0<DataType extends Object> extends _i1.SmartFake
    implements _i2.IResponseResult<DataType> {
  _FakeIResponseResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [IAstronomicalMediaUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockIAstronomicalMediaUsecase extends _i1.Mock
    implements _i3.IAstronomicalMediaUsecase {
  @override
  _i4.Future<_i2.IResponseResult<_i5.AstronomicalMediaModel>> getMedia(
    DateTime? date,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMedia, [date]),
            returnValue: _i4.Future<
              _i2.IResponseResult<_i5.AstronomicalMediaModel>
            >.value(
              _FakeIResponseResult_0<_i5.AstronomicalMediaModel>(
                this,
                Invocation.method(#getMedia, [date]),
              ),
            ),
            returnValueForMissingStub: _i4.Future<
              _i2.IResponseResult<_i5.AstronomicalMediaModel>
            >.value(
              _FakeIResponseResult_0<_i5.AstronomicalMediaModel>(
                this,
                Invocation.method(#getMedia, [date]),
              ),
            ),
          )
          as _i4.Future<_i2.IResponseResult<_i5.AstronomicalMediaModel>>);
}

/// A class which mocks [AstronomicalMediaModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockAstronomicalMediaModel extends _i1.Mock
    implements _i5.AstronomicalMediaModel {
  @override
  String get date =>
      (super.noSuchMethod(
            Invocation.getter(#date),
            returnValue: _i6.dummyValue<String>(this, Invocation.getter(#date)),
            returnValueForMissingStub: _i6.dummyValue<String>(
              this,
              Invocation.getter(#date),
            ),
          )
          as String);

  @override
  String get explanation =>
      (super.noSuchMethod(
            Invocation.getter(#explanation),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#explanation),
            ),
            returnValueForMissingStub: _i6.dummyValue<String>(
              this,
              Invocation.getter(#explanation),
            ),
          )
          as String);

  @override
  String get hdUrl =>
      (super.noSuchMethod(
            Invocation.getter(#hdUrl),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#hdUrl),
            ),
            returnValueForMissingStub: _i6.dummyValue<String>(
              this,
              Invocation.getter(#hdUrl),
            ),
          )
          as String);

  @override
  _i7.MediaType get mediaType =>
      (super.noSuchMethod(
            Invocation.getter(#mediaType),
            returnValue: _i7.MediaType.image,
            returnValueForMissingStub: _i7.MediaType.image,
          )
          as _i7.MediaType);

  @override
  String get title =>
      (super.noSuchMethod(
            Invocation.getter(#title),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#title),
            ),
            returnValueForMissingStub: _i6.dummyValue<String>(
              this,
              Invocation.getter(#title),
            ),
          )
          as String);

  @override
  String get url =>
      (super.noSuchMethod(
            Invocation.getter(#url),
            returnValue: _i6.dummyValue<String>(this, Invocation.getter(#url)),
            returnValueForMissingStub: _i6.dummyValue<String>(
              this,
              Invocation.getter(#url),
            ),
          )
          as String);

  @override
  List<Object?> get props =>
      (super.noSuchMethod(
            Invocation.getter(#props),
            returnValue: <Object?>[],
            returnValueForMissingStub: <Object?>[],
          )
          as List<Object?>);
}
